RubyOnRails/config/routes.rb
Rails.application.routes.draw do

  get 'rails/routes'
  # root admin sign ups/logins
  root 'registrations#new'
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # admin sign ins / logouts
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # admin_home 
  get "admin_home", to: "admin#index"

  # eval controllers
  # resources :evaluations
  # admin eval views
  post 'create_evaluation', to: 'evaluations#create'
  delete 'delete_evaluation', to: 'evaluations#remove'
  get 'view_evaluation', to: 'evaluations#view'
  # user eval views 
  get "user_eval", to: "users#index_eval"
  get 'user_view', to: 'users#view'
  get 'edit_eval', to: 'evaluations#edit'
  patch 'user_eval', to: 'evaluations#update'

  # user home page and group routes
  get "user_home", to: "users#home"
  get "user_group", to: "users#index_group"
  get "score", to: "users#score"


  #project controllers
  resources :projects
  #assign projects to groups 
  get "assign_group", to: "projects#assign_group"
  post "assign_group", to: "projects#create_proj_group"
  delete "assign_group", to: "projects#remove_group"
  
  # create users
  resources :users

  # group and grouping controllers
  resources :groups 
  get 'add_to_group', to: 'groups#add_user' 
  post 'add_to_group', to: 'groups#create_grouping'
  delete 'add_to_group', to: 'groups#remove_user'
  
  # main login page root
  # root 'sessions#login'

  

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

RubyOnRails/app/models/group.rb
class Group < ApplicationRecord
    has_many :groupings
    has_many :users, through: :groupings

    has_many :project_groups
    has_many :projects, through: :project_groups
end

RubyOnRails/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    if session[:admin_id]
      @admin = Admin.find_by(id: session[:admin_id])
    end
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @groupUsers = @group.users
  end

  # add a user to group page controller
  def add_user
    @users = User.all
    @group = Group.find_by(id: params[:gid])
    @groupUsers = @group.users
  end

  # creates a user to group pairing
  def create_grouping
    # render plain: params[:gid]
    @grouping = Grouping.new( {user_id: params[:uid], group_id: params[:gid]})
    @users = User.all
    @group = Group.find_by(id: params[:gid])
    @groupUsers = @group.users
    if @grouping.save
      render :add_user, notice: "Successfully added"
    else
      render :add_user
    end
  end
    
  # remove user from grouping to page.
  def remove_user
    @grouping = Grouping.find_by({user_id: params[:uid], group_id: params[:gid]})
    @grouping.destroy
    @users = User.all
    @group = Group.find_by(id: params[:gid])
    @groupUsers = @group.users
    flash[:success] = "The user was successfully removed from group."
    render :add_user
  end
  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def user_groups
    @user=User.find_by(id: session[:user_id])
    @Usergroup=@user.groups
  end

  def show_user_groups
    @group=Group.find_by(params[:id])
    @groupUsers=@group.users
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end

   
    
end

RubyOnRails/app/helpers/groups_helper.rb
module GroupsHelper
end

RubyOnRails/app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "McDonalds" %>
  </div>

  <div class="submit">
    <%= form.submit "Add Group", class: "btn btn-primary" %>
  </div>
<% end %>

RubyOnRails/app/views/groups/add_user.html.erb
<% if flash[:success] %>
      <div class="alert alert-primary" id="alert">
         <%= flash[:success] %> 
      </div>
<% end %>
<div class ="row">
    <div class="col-xs-6">   
        <h2 class="sub-header">Class</h2>
        <div class="table-responsive">
            <table class ="table table-striped">
            <thead>
                <tr>
                <th>Name</th>
                <th>Email</th>
                <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @users.each do |user| %>
                <tr>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= link_to 'Join Group', add_to_group_path(uid: user.id, gid: @group.id), method: :post, class: "btn btn-danger"%></td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>

    <div class="col-xs-6">   
        <h2 class="sub-header">Group</h2>
        <div class="table-responsive">
            <table class ="table table-striped">
            <thead>
                <tr>
                <th>Name</th>
                <th>Email</th>
                <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @groupUsers.each do |user| %>
                <tr>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= link_to 'Remove', add_to_group_path(uid: user.id, gid: @group.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>
</div>

<%= link_to 'Back', group_url(id: @group.id) %>

RubyOnRails/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

RubyOnRails/app/views/groups/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"admin_home", admin_home_path, class: "nav-link" %>
          <a class="nav-link" href="/admin_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/groups">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/projects">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users">Users</a>
        </li>
        <% if @admin %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @admin.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>


<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show Members', group , class: "btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_group_path(group),class: "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path,class: "btn btn-primary" %>

RubyOnRails/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

RubyOnRails/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>
<h1> List of Group Members</h1>
<table class ="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groupUsers.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Remove', add_to_group_path(gid: @group.id, uid: user.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %> |
<%= link_to 'Add Members', add_to_group_url(gid: @group.id), class: "btn btn-secondary"%>

RubyOnRails/app/views/groups/show_user_groups.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>
<h1> List of Group Members1</h1>
<table class ="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groupUsers.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', user_groups_path %> |

RubyOnRails/app/views/groups/user_groups.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link" href="/user_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="users_groups">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/show_user_projects">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/evaluations">Evaluations</a>
        </li>
        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>


<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th>Group Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @Usergroup.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show Members', show_group_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>