RubyOnRails/config/routes.rb
Rails.application.routes.draw do

  get 'rails/routes'
  # root admin sign ups/logins
  root 'registrations#new'
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # admin sign ins / logouts
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # admin_home 
  get "admin_home", to: "admin#index"

  # eval controllers
  # resources :evaluations
  # admin eval views
  post 'create_evaluation', to: 'evaluations#create'
  delete 'delete_evaluation', to: 'evaluations#remove'
  get 'view_evaluation', to: 'evaluations#view'
  # user eval views 
  get "user_eval", to: "users#index_eval"
  get 'user_view', to: 'users#view'
  get 'edit_eval', to: 'evaluations#edit'
  patch 'user_eval', to: 'evaluations#update'

  # user home page and group routes
  get "user_home", to: "users#home"
  get "user_group", to: "users#index_group"
  get "score", to: "users#score"


  #project controllers
  resources :projects
  #assign projects to groups 
  get "assign_group", to: "projects#assign_group"
  post "assign_group", to: "projects#create_proj_group"
  delete "assign_group", to: "projects#remove_group"
  
  # create users
  resources :users

  # group and grouping controllers
  resources :groups 
  get 'add_to_group', to: 'groups#add_user' 
  post 'add_to_group', to: 'groups#create_grouping'
  delete 'add_to_group', to: 'groups#remove_user'
  
  # main login page root
  # root 'sessions#login'

  

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

RubyOnRails/app/models/user.rb
class User < ApplicationRecord
    has_many :groupings
    has_many :groups, through: :groupings
    has_many :evaluations

    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[a-z]+.[1-9]\d*@osu.edu/i
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: true

    validates :password, presence: true, length: { minimum: 2 }
end

RubyOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    if session[:admin_id]
      @admin = Admin.find_by(id: session[:admin_id])
    end
    @users = User.all
    
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_eval
    @evaluation= Evaluation.new
  end

def create_eval
  if session[:user_id]
    @user = User.find_by(id: session[:user_id])
  end
  @evaluation = Evaluation.new(projects_params)
  if @evaluation.save 
      redirect_to evaluation_path, notice: "Successfully created eval"
  else
    render :new_eval
  end
end

  #GET user/home
  def home
    @user = User.find_by(id: session[:user_id])
    # now using the user found, chain id scan from group to group to every respective project.
    @userGroups = @user.groups
    @projects = []
    @groups = []
    @userGroups.each do |group|
      groupProjects = group.projects
      groupProjects.each do |project|
        @projects.append([project, group])
      end
    end

  end
  
  # user view for groups
  def index_group
    @user=User.find_by(id: session[:user_id])
    @Usergroup = @user.groups
  end

  # user edit controller for evaluations
  def index_eval
    @user = User.find_by(id: session[:user_id])
    @project = Project.find_by(id: params[:pid])
    @evaluations = Evaluation.all 
  end

  # user view for evaluations
  def view
    @user = User.find_by(id: session[:user_id])
    @project = Project.find_by(id: params[:pid])
    @evaluations = Evaluation.all 
  end

  #use this parameters list during updates or creation of evals
  def evaluation_params
    params.require(:evaluation).permit(:evaluee,:context, :rating, :commit)
  end
  
  def score
    @user = User.find_by(id: session[:user_id])
    @project = Project.find_by(id: params[:pid])
    @evaluations = Evaluation.all 
    @evaluation= Evaluation.new
    #print out the score average for semester
    @score =0 
    @projs = []
    @scoring = {}
   
    
    count = 0 
   
    @userGroups = @user.groups 
    @userGroups.each do |group| 
      @projects = group.projects
      @projects.each do |proj|
        average = 0 
        @evaluations = Evaluation.where(pid: proj.id)
        counting =0
        @evaluations.each do |eval|
          if eval.receiverid == @user.id
            average += eval.rating
            counting +=1
          end

        end

        if(counting>0)
          average /=counting
        end

        @projs.append(average)
      end
    end

    @evaluations = Evaluation.all
    count = 0 
    @evaluations.each do |eval|
      
      if(User.find(eval.receiverid).id== @user.id)
        @score += eval.rating 
        count +=1
      end
    end
    if(count > 0 )
      @score /=count
    else
      @score = 0 
    end 
    #print out averages for project
    
  end 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

RubyOnRails/app/helpers/user_helper.rb
module UserHelper
end

RubyOnRails/app/helpers/users_helper.rb
module UsersHelper
end

RubyOnRails/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.text_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "New User", class: "btn btn-primary"%>
  </div>
<% end %>

RubyOnRails/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class: "btn btn-dark"%> |
<%= link_to 'Back', users_path, class: "btn btn-secondary" %>

RubyOnRails/app/views/users/home.html.erb
<style>
.collapse.show {
  visibility: visible;
}
</style>
<%# require 'date' #require if not already required %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link active" aria-current="page" href="/user_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user_group">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/score">Average Scores</a>
        </li>
        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

<body>
<div class="content">
    <h1 class = "d-flex align-items-center justify-content-center"><%=@user.name %>'s Evaluations</h1>
    <p>Welcome back!</p>
    <br>
    <h2 class = "align-items-center justify-content-center"> Today's Date: <%= Date.current %> </h2>
    <br>
    <br>
    <h3>Evaluations To-do</h3>
  <!-- Print out all projects that are due at this moment based on project due date -->
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <% @projects.each do |project, group| %>
      <% if !(project.date.to_date.past?)%>
      <%# if Date.current <= DateTime.strptime(project.date, "%D") %>
      
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <h5> Project <%= project.projectname %> </h5>
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <table class="table">
            <thead>
              <tr>
                <th>Group Name</th>
                <th colspan="3"></th>
                <th colspan="3"></th>
              </tr>
            </thead>
              <tbody>
                <tr>
                  <td> <%= group.name  %></td>
                  <td> <%= link_to 'Edit Evaluations', user_eval_path(pid: project.id),class: "btn btn-secondary" %>  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
    </div>
        
    <!-- Print out all projects that are not due at this moment based on project due date -->

    <h3> Past Evaluations </h3>
     <% @projects.each do |project, group| %>
      <% if (project.date.to_date.past?)%>
      <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Project <%= project.projectname %>
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <table class="table">
            <thead>
              <tr>
                <th>Group Name</th>
                <th colspan="3"></th>
                <th colspan="3"></th>
              </tr>
            </thead>
              <tbody>
                <tr>
                  <td> <%= group.name  %></td>
                  <td> <%= link_to 'View Evaluations', user_view_path(pid: project.id), class: "btn btn-primary" %> </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
</div>
</body>

RubyOnRails/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"admin_home", admin_home_path, class: "nav-link" %>
          <a class="nav-link" href="/admin_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/groups">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/projects">Projects</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/users">Users</a>
        </li>
        <% if @admin %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @admin.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

<h1>Users</h1>
<% @users.each do |user| %>
  <% if !(@users.name == nil)%>

    <table class ="table table-striped table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Password</th>
          
        </tr>
      </thead>

      <tbody>
      
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.password %></td>
            <td><%= link_to 'Show', user, class: "btn btn-secondary"%></td>
            <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary" %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
          </tr>
      </tbody>
    </table>
  <%end%>
<% end %>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary" %>

RubyOnRails/app/views/users/index_eval.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link active" aria-current="page" href="/user_home">Home</a>
        </li>
        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<h1>Evaluations</h1>
<table class = "table">
  <thead>
    <tr>
      <th>Evaluator</th>
      <th>Evaluee</th>
      <th>Context</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
    
      <tr>
        <% if User.find(evaluation.senderid).id == @user.id && evaluation.pid == @project.id %>
          <td><%= User.find(evaluation.senderid).name%></td>
          <td><%= evaluation.evaluee %></td>
          <td><%= evaluation.context %></td>
          <td><%= evaluation.rating %></td>
          <td><%= link_to 'Edit', edit_eval_path(id: evaluation.id) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<h4> Constraints </h4>
<p>
The total number of points you allocate for your
<strong>group must be less than or equal to 7 * n </strong>, where n is the
number of people in your group.  In the example below, there
are 4 people so the total of points must be <= 28.
 </p>


<h4>  Instructions  </h4>
<ol>
  <li>Cut out the text indicated below and use as a template.</li>
  <li>Complete the form, rating each person in your group on a
        scale of 0 to 10.  (See constraint and rubric below.)</li>
  <li>Rate **yourself** on the same scale.</li>
  <li>Add comments to clarify/justify your evaluation.</li>
  <li>Email the completed form to the grader(s).</li>
</ol> 

<table class ="table">
  <thead class="thead-dark">
    <tr>
      <th>Rating </th>
      <th>Explanation</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>9-10</td>
      <td>Amazing team-mate You will be in contact with them for years One of the **best** team-mates you have ever had for any project</td>
    </tr>
    <tr>
      <td>7-8</td>
      <td>Very good team-mate
      Contributed significantly
      Communicated effectively
      Took initiative in the design and implementation
      You would **seek out** this person to be a team-mate in a future course
      </td>
    </tr>
    <tr>
      <td>5-6</td>
      <td>Good team-mate
      Carried out their assigned responsibilities
      Contributed to the final product
      Room for improvement in communication, initiative, effort, or skills
      You would be **willing to partner** with them in a future course, though you wouldn't seek them out  
      </td>
    </tr>
    <tr>
      <td>3-4</td>
      <td>Fair team-mate
      Worked hard at contributing to the project
      Struggled to carry out assigned responsibilities
      Made minor contributions to the final product
      You would **prefer not to partner** with this person in a future course
      </td>
    </tr>
    <tr>
      <td>0-3</td>
      <td>Poor team-mate
      Did not contribute to the final product
      Put forth little or insufficient effort
      Was rarely present at team meetings and was difficult to get a hold of
      You would **avoid partnering** with this person in a future course
      </td>
    </tr>
  </tbody>
</table>

RubyOnRails/app/views/users/index_group.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link active" aria-current="page" href="/user_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user_group">Groups</a>
        </li>

        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th>Group Names</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @Usergroup.each do |group| %>
      <tr>
        <td><%= group.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

RubyOnRails/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

RubyOnRails/app/views/users/score.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link active" aria-current="page" href="/user_home">Home</a>
        </li>
        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

<!--Adding scoring feature to the Average Scores Tab -->
<h1><%=@user.name%>'s Average Scores</h1>


<br>
    <h5>Your Average Score for This Semester: <%=@score%><h5>
     <%count = 1 %>
     <%@projs.each do |sc|%>
     <p>Project <%=count %> Average is: <%=sc%></p>
     <%count +=1%>
     <%end%>

    

RubyOnRails/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-primary"%> |
<%= link_to 'Back', users_path, class:"btn btn-secondary"  %>

RubyOnRails/app/views/users/view.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link active" aria-current="page" href="/user_home">Home</a>
        </li>
        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<h1>Evaluations</h1>
<table class = "table">
  <thead>
    <tr>
      <th>Evaluator</th>
      <th>Evaluee</th>
      <th>Context</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
    <%# if @user.name == %>
      <tr>
        <% if User.find(evaluation.senderid).id == @user.id && evaluation.pid == @project.id %>
          <td><%= User.find(evaluation.senderid).name%></td>
          <td><%= evaluation.evaluee %></td>
          <td><%= evaluation.context %></td>
          <td><%= evaluation.rating %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>