RubyOnRails/config/routes.rb
Rails.application.routes.draw do

  get 'rails/routes'
  # root admin sign ups/logins
  root 'registrations#new'
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # admin sign ins / logouts
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # admin_home 
  get "admin_home", to: "admin#index"

  # eval controllers
  # resources :evaluations
  # admin eval views
  post 'create_evaluation', to: 'evaluations#create'
  delete 'delete_evaluation', to: 'evaluations#remove'
  get 'view_evaluation', to: 'evaluations#view'
  # user eval views 
  get "user_eval", to: "users#index_eval"
  get 'user_view', to: 'users#view'
  get 'edit_eval', to: 'evaluations#edit'
  patch 'user_eval', to: 'evaluations#update'

  # user home page and group routes
  get "user_home", to: "users#home"
  get "user_group", to: "users#index_group"
  get "score", to: "users#score"


  #project controllers
  resources :projects
  #assign projects to groups 
  get "assign_group", to: "projects#assign_group"
  post "assign_group", to: "projects#create_proj_group"
  delete "assign_group", to: "projects#remove_group"
  
  # create users
  resources :users

  # group and grouping controllers
  resources :groups 
  get 'add_to_group', to: 'groups#add_user' 
  post 'add_to_group', to: 'groups#create_grouping'
  delete 'add_to_group', to: 'groups#remove_user'
  
  # main login page root
  # root 'sessions#login'

  

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

RubyOnRails/app/models/evaluation.rb
class Evaluation < ApplicationRecord
  # belongs_to :users
  # belongs_to :projects
 
 
 validates :evaluee, presence:true, length:{ maximum:150 }
 validates :context, presence:true, length:{maximum:150}
 validates :rating, numericality: {only_integer: true}
 
end

RubyOnRails/app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController 
    #For a page to list all evaluations ( GET) 
    # Named route: evaluations_path 
    def index
        @evaluations = Evaluation.all 
    end 

    #For a page to show evaluation (GET)
    #Named route: evaluation_path(evaluation)
    def show 
        @evaluation = Evaluation.find(params[:id])
    end 

    #For a page to make a new evaluation (GET)
    #Named route: evaluations_path
    def new 
        @evaluations = Evaluation.new 
    end

    #To create a new evaluation (POST)
    #Named route: evaluation path 
    def create 
        @project = Project.find_by(id: params[:pid]) # find respective project for all the evaluations
        @projectGroups = @project.groups
        @projectGroups.each do |group|  # basically go through chain of associations to create all respective evaluations between users.
            groupUsers = group.users
            groupUsers.each do |sendUser|
                groupUsers.each do |receiveUser|
                    @evaluation = Evaluation.create(evaluee: receiveUser.name, context: "blank context", rating: 0, senderid: sendUser.id, receiverid: receiveUser.id, pid: @project.id)
                    if @evaluation.save!
                    else
                        flash[:alert] = "Error Unable to Assign Evaluations!"
                        @project.update(assigned: 0)
                    end
                end
            end
        end
        @project.update(assigned: 1) # update boolean to show that evaluations have been assigned
        redirect_to projects_path # go back to project screen with an updated view.
    end

    def view
        @evaluations = [] # super inefficient right now, will need to figure out a good way to assign foreign key indexing from proj to evals
        @project = Project.find_by(id: params[:pid]) # find respective project for all the evaluations
        @projectGroups = @project.groups
        @projectGroups.each do |group|  # basically go through chain of associations to create all respective evaluations between users.
            groupUsers = group.users
            groupUsers.each do |sendUser|
                groupUsers.each do |receiveUser|
                    evaluation = Evaluation.find_by(senderid: sendUser.id, receiverid: receiveUser.id, pid: @project.id)
                    evalData = [sendUser.name, receiveUser.name, evaluation.rating, evaluation.context]
                    @evaluations.append(evalData)
                end
            end
        end
    end
    #For a page to edit evaluation with specific id number(GET)
    # Name route: edit evaluation_path(evaluation)
    def edit 
        @evaluation = Evaluation.find(params[:id])
    end 

    #To update an evaluation (PATCH)
    #Named route: evaluation_path(evaluation)
    def patch 
    end 

    #Delete an evaluation 
    def remove
        @project = Project.find_by(id: params[:pid]) # find respective project for all the evaluations
        @projectGroups = @project.groups
        @projectGroups.each do |group|  # basically go through chain of associations to create all respective evaluations between users.
            groupUsers = group.users
            groupUsers.each do |sendUser|
                groupUsers.each do |receiveUser|
                    evaluation = Evaluation.find_by(senderid: sendUser.id, receiverid: receiveUser.id, pid: @project.id)
                    if !(evaluation.nil?)
                        evaluation.destroy # destroy all them evals.
                    end
                end
            end
        end
        @project.update(assigned: 0) # update boolean to show that evaluations have not been assigned
        redirect_to projects_path(pid: @project.id) # go back to project screen with an updated view.
    end

    def update 
        @evaluation = Evaluation.find(params[:id])
        # check to make sure parameter inputs are below the total 7*n requirement, else throw an error message 
        @evaluations = Evaluation.where(senderid: @evaluation.senderid, pid: @evaluation.pid)
        totalRating = 0
        @evaluations.each do |previousEval| # sum total rating scores up first.
            totalRating += previousEval.rating 
        end
        totalRating += (params[:evaluation][:rating].to_i - @evaluation.rating)

        # check valid else or throw an error
        if (totalRating <= 7 * @evaluations.length) && (params[:evaluation][:rating].to_i <= 10) && @evaluation.update(context: params[:evaluation][:context], rating: params[:evaluation][:rating].to_i)
            redirect_to user_eval_path(pid: @evaluation.pid)
        else
            Rails.logger.info(@evaluation.errors.messages.inspect)
            flash[:alert] = "Unable to Update Evaluation, Invalid Input! Either empty input, greater than 10 rating, or total evaluations are greater than 7*n score"
            render :edit
        end
    end 


    #authorization check points
    def evaluation_params
        params.require(:evaluation).permit(:evaluee, :context, :rating,:senderid, :receiverid,:pid)
    end
end

RubyOnRails/app/views/evaluations/_form.html.erb
<%= form_with(model: evaluation) do |form| %>


   <div class="field">
    <%= form.label :evaluee %>
    <%= form.text_area :evaluee%>
  </div>

  <div class="field">
    <%= form.label :context %>
    <%= form.text_area :context %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>
  <div class="submit">
    <%= form.submit "Add Group", class: "btn btn-primary" %>
  </div>
<% end %>

RubyOnRails/app/views/evaluations/edit.html.erb
<% if flash[:alert] %>
      <div class="alert alert-primary" id="alert">
         <%= flash[:alert] %> 
      </div>
<% end %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link active" aria-current="page" href="/user_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user_group">Groups</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/user_eval">Evaluations</a>
        </li>
        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>


<h1>Editing Evaluation for Evaluee <%= User.find(@evaluation.receiverid).name%></h1>

<%= form_with model: @evaluation, url:user_eval_path(id: @evaluation.id), method: "patch", local: true do |form|%>
  <div class="field">
    <%= form.label :context %>
    <%= form.text_area :context %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="submit">
    <%= form.submit "Update Evaluation", class: "btn btn-primary" %>
  </div>
<%end%>

<%= link_to 'Back', user_eval_path(pid: @evaluation.pid) %>

RubyOnRails/app/views/evaluations/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"user_home", user_home_path, class: "nav-link" %>
          <a class="nav-link active" aria-current="page" href="/user_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user_group">Groups</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/user_eval">Evaluations</a>
        </li>
        <% if @user %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @user.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>


<h1>Evaluations</h1>
<table class = "table">
  <thead>
    <tr>
      <th>Evaluee</th>
      <th>Context</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= evaluation.evaluee %></td>
        <td><%= evaluation.context %></td>
        <td><%= evaluation.rating %></td>
        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

RubyOnRails/app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

RubyOnRails/app/views/evaluations/view.html.erb
<h1>All Evaluations Page</h1>
<body>

  <% @projectGroups.each do |group|%>
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <h5> Group <%= group.name %> </h5>
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <table class="table table-striped table-bordered table-hover">
              <thead class="thead-dark">
                <tr>
                  <th>Evaluator</th>
                  <th>Evaluee Name</th>
                  <th>Score</th>
                  <th>Comment</th>
                  <th>Project</th>
                </tr>
            </thead>
              <tbody>
                <% group.users.each do |user| %>
                  <tr>
                    <% Evaluation.where(senderid: user.id).each do |eval|%>
                        <tr>
                        <td> <%= user.name %></td>
                        <td> <%= eval.evaluee %></td>
                        <td> <%= eval.rating %></td>
                        <td> <%= eval.context %></td>
                        <td><%= Project.find(eval.pid).projectname%></td>
                        </tr>
                    <% end %>
                <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  <% end %>

<%= link_to 'Back', projects_path, class:"btn btn-secondary" %>
</body>