RubyOnRails/config/routes.rb
Rails.application.routes.draw do

  get 'rails/routes'
  # root admin sign ups/logins
  root 'registrations#new'
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # admin sign ins / logouts
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # admin_home 
  get "admin_home", to: "admin#index"

  # eval controllers
  # resources :evaluations
  # admin eval views
  post 'create_evaluation', to: 'evaluations#create'
  delete 'delete_evaluation', to: 'evaluations#remove'
  get 'view_evaluation', to: 'evaluations#view'
  # user eval views 
  get "user_eval", to: "users#index_eval"
  get 'user_view', to: 'users#view'
  get 'edit_eval', to: 'evaluations#edit'
  patch 'user_eval', to: 'evaluations#update'

  # user home page and group routes
  get "user_home", to: "users#home"
  get "user_group", to: "users#index_group"
  get "score", to: "users#score"


  #project controllers
  resources :projects
  #assign projects to groups 
  get "assign_group", to: "projects#assign_group"
  post "assign_group", to: "projects#create_proj_group"
  delete "assign_group", to: "projects#remove_group"
  
  # create users
  resources :users

  # group and grouping controllers
  resources :groups 
  get 'add_to_group', to: 'groups#add_user' 
  post 'add_to_group', to: 'groups#create_grouping'
  delete 'add_to_group', to: 'groups#remove_user'
  
  # main login page root
  # root 'sessions#login'

  

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

RubyOnRails/app/models/project.rb
class Project < ApplicationRecord
    has_many :project_groups
    has_many :groups, through: :project_groups
    
    
    validates :date, presence: true, length:{minimum: 10},   
        uniqueness: true
end

RubyOnRails/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    if session[:admin_id]
      @admin = Admin.find_by(id: session[:admin_id])
    end
    @projects = Project.all
  end

  # project assignment page.
  def show
    @project = Project.find(params[:id])
    @projectGroups = @project.groups
  end

  # assign group to project get page controller
  def assign_group
    @groups = Group.all
    @project = Project.find_by(id: params[:pid])
    @projectGroups = @project.groups
  end

  # create project group pairing
  def create_proj_group
    @projectGroup = ProjectGroup.new( {project_id: params[:pid], group_id: params[:gid]})
    @groups = Group.all
    @project = Project.find_by(id: params[:pid])
    @projectGroups = @project.groups
    if @projectGroup.save
      render :assign_group, notice: "Successfully assigned!"
    else
      render :assign_group
    end
  end

  # remove groups from group to project pairing
  def remove_group
    @projectGroup = ProjectGroup.find_by( {project_id: params[:pid], group_id: params[:gid]})
    @projectGroup.destroy
    @groups = Group.all
    @project = Project.find_by(id: params[:pid])
    @projectGroups = @project.groups
    flash[:success] = "Group Successfully Removed From Project"
    render :assign_group
  end
  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
       
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @associatedEvals = Evaluation.where(pid: @project.id)
    @associatedEvals.each do |eval|
      eval.destroy # cascading destroy for evals
    end

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show_user_projects
    @project=Project.find(params[:pid])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:projectname, :projecttype, :date, :added) # note the added variable is supposed to represent true/false
    end
end

RubyOnRails/app/helpers/projects_helper.rb
module ProjectsHelper
end

RubyOnRails/app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="alert alert-danger">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :Projectname, 'Project Name' %>
    <%= form.text_field :projectname, class: "form-control", placeholder: "Game of Set" %>
  </div>

  <div class="mb-3 ">
    <%= form.label :projecttype , 'Project Type'%>
    <%= form.text_field :projecttype, class: "form-control", placeholder: "Tech Groups" %>
  </div>
  <br>
<p>Please enter a valid date in the formate below </p>
  <div class="mb-3">
    <%= form.label :date, 'Deadline  ' %>
    <%= form.text_field :date, class: "form-control", placeholder: "2002-01-02" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit "Add Project", class: "btn btn-primary" %>
  </div>
<% end %>

RubyOnRails/app/views/projects/assign_group.html.erb
<p id="notice"><%= notice %></p>
<% if flash[:success] %>
      <div class="alert alert-primary" id="alert">
         <%= flash[:success] %> 
      </div>
<% end %>
<%
=begin%>
  Specialized styling for the double side by side tables. 
<%
=end%>
<style>
* {
  box-sizing: border-box;
}

.row {
  margin-left:-5px;
  margin-right:-5px;
}
  
.column {
  float: left;
  width: 50%;
  padding: 5px;
}

/* Clearfix (clear floats) */
.row::after {
  content: "";
  clear: both;
  display: table;
}

table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 16px;
}

tr:nth-child(even) {
  background-color: #f2f2f2;
}
</style>
</head>
<body>

<h2>Assign Groups to Projects</h2>

<div class="row">
  <div class="column">
    <h2> List of Groups </h2>
    <table>
        <tr>
            <th>Name</th>
        </tr>
        <tbody>
                <% @groups.each do |group| %>
                <tr>
                    <td><%= group.name %></td>
                    <td><%= link_to 'Assign Group', assign_group_path(gid: group.id, pid: @project.id), method: :post, class: "btn btn-danger"%></td>
                </tr>
                <% end %>
        </tbody>
    </table>
  </div>
  <div class="column">
    <h2> Assigned Groups </h2>
    <table>
        <tr>
            <th>Name</th>
        </tr>
        <tbody>
                <% @projectGroups.each do |group| %>
                <tr>
                    <td><%= group.name %></td>
                    <td><%= link_to 'Remove', assign_group_path(gid: group.id, pid: @project.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
                </tr>
                <% end %>
        </tbody>
    </table>
  </div>
</div>

<%= link_to 'Back', project_url(id: @project.id),class: "btn btn-secondary" %>

RubyOnRails/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project, class: "btn btn-secondary" %> 
<% link_to 'Destroy', @project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>
<%= link_to 'Back', projects_path,  class: "btn btn-dark" %>

RubyOnRails/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%link_to"admin_home", admin_home_path, class: "nav-link" %>
          <a class="nav-link" href="/admin_home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/groups">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/projects">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users">Users</a>
        </li>
        <% if @admin %>
          <li class="nav-item">
            <a class="nav-link"> Logged in as <%= @admin.email %>   
             </a>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete %>
          </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

<h1>Projects</h1>

<table class ="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.projectname %></td>
        <td><%= project.projecttype %></td>
        <td><%= project.date %></td>
        <td><%= link_to 'Show Assigned Groups', project, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_project_path(project), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <td>
        <% if project.assigned == 1 %>
         <%= link_to 'Remove Evaluations', delete_evaluation_path(pid: project.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
        <% else %>
          <%= link_to 'Assign Evaluations', create_evaluation_path(pid: project.id), method: :post, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% end %>
        </td>
        <td>
        <% if project.assigned == 1 %>
         <%= link_to 'View Evaluations', view_evaluation_path(pid: project.id), method: :get, class: "btn btn-secondary" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>

RubyOnRails/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, class: "btn btn-secondary" %>

RubyOnRails/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.projectname %>
</p>

<p>
  <strong>Type:</strong>
  <%= @project.projecttype %>
</p>

<p>
  <strong>Date:</strong>
  <%= @project.date %>
</p>

<h1> List of Groups Assigned</h1>
<table class ="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projectGroups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'Assign Groups', assign_group_url(pid: @project.id), class: "btn btn-secondary" %>

RubyOnRails/app/views/projects/show_user_projects.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projectname:</strong>
  <%= @project.projectname %>
</p>

<p>
  <strong>Projecttype:</strong>
  <%= @project.projecttype %>
</p>

<p>
  <strong>Date:</strong>
  <%= @project.date %>
</p>

<%= link_to 'Back', projects_path %>